In [33]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### Step 1: Import Data 

The "real_estate_valuation_data_set.csv" file saves the market historical data of real estate valuation of a Chinese city. The variable information is as follows 

| Variable Name | Role | Type | Description | Units | 
|:--|:--|:--|:--|:--|
|No|ID|Integer||||
|X1 transaction date|Feature|Continuous|for example, 2013.250=2013 March, <br>2013.500=2013 June, etc.||
|X2 house age|Feature|Continuous||year|
|X3 distance to the <br>nearest metro station|Feature|Continuous||meter|
|X4 number of <br>convenience stores|Feature|Integer|number of convenience stores in the<br> living circle on foot|integer|
|X5 latitude|Feature|Continuous|geographic coordinate, latitude|degree|
|X6 longitude|Feature|Continuous|geographic coordinate, longitude|degree|
|Y house price of<br> unit area|Target|Continuous|10000 Chinese Yuan per <br>square metre|10000 CNY/<br>square metre|

In [34]:
# Read the data with pandas
real_estate = pd.read_csv("real_estate_valuation_data_set.csv", index_col=0)

In [35]:
# Show the first five rows of the data
real_estate.head()

X1 transaction date  X2 house age  X3 distance to the nearest MRT station  \
No                                                                              
1              2012.917          32.0                                84.87882   
2              2012.917          19.5                               306.59470   
3              2013.583          13.3                               561.98450   
4              2013.500          13.3                               561.98450   
5              2012.833           5.0                               390.56840   

    X4 number of convenience stores  X5 latitude  X6 longitude  \
No                                                               
1                                10     24.98298     121.54024   
2                                 9     24.98034     121.53951   
3                                 5     24.98746     121.54391   
4                                 5     24.98746     121.54391   
5                                 5     24.97937     121.54245   

    Y house price of unit area  
No                              
1                         2.53  
2                         2.81  
3                         3.15  
4                         3.65  
5                         2.87

In [36]:
# Get the number of instances and features
row_num = real_estate.shape[0]
col_num = real_estate.shape[1]

In [37]:
row_num, col_num

(414, 7)

In [38]:
# Get the input variables X with features from X1 to X6.
X = np.array(real_estate.iloc[:,:6].values)

In [39]:
X.shape

(414, 6)

In [40]:
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]], shape=(414, 6))

In [41]:
# Get the target values y
y = np.array(real_estate.iloc[:,6].values)

In [42]:
y.shape

(414,)

In [43]:
y

array([2.53, 2.81, 3.15, 3.65, 2.87, 2.14, 2.69, 3.11, 1.25, 1.47, 2.76,
       3.87, 2.62, 1.59, 2.29, 3.37, 4.67, 2.49, 2.82, 3.18, 1.95, 3.44,
       1.64, 3.19, 2.59, 1.8 , 3.75, 2.24, 3.13, 3.81, 1.47, 1.67, 2.28,
       3.29, 3.67, 1.82, 1.53, 1.69, 3.18, 3.08, 1.06, 1.21, 2.31, 2.27,
       3.59, 2.55, 2.8 , 4.1 , 0.89, 0.88, 2.95, 1.38, 1.8 , 2.59, 3.45,
       0.91, 2.79, 3.57, 1.51, 2.83, 1.42, 4.21, 1.85, 3.67, 1.69, 2.95,
       3.38, 3.79, 2.41, 2.8 , 3.93, 2.72, 2.42, 1.33, 3.63, 1.97, 2.45,
       1.71, 1.99, 1.77, 2.69, 2.45, 3.21, 1.18, 2.91, 3.39, 1.8 , 1.22,
       3.2 , 1.69, 3.03, 2.88, 1.45, 1.07, 2.73, 3.45, 3.97, 2.31, 3.4 ,
       4.15, 2.55, 2.19, 3.63, 3.05, 2.03, 4.73, 3.14, 1.77, 2.27, 1.89,
       3.44, 2.63, 1.54, 0.51, 3.55, 3.09, 0.81, 0.87, 2.04, 3.97, 2.09,
       3.2 , 2.17, 3.03, 3.83, 3.24, 4.19, 3.67, 4.05, 2.73, 2.5 , 2.05,
       2.5 , 2.63, 2.81, 1.39, 3.12, 3.16, 2.9 , 2.83, 3.43, 1.93, 2.5 ,
       2.67, 1.89, 3.03, 3.48, 2.88, 3.01, 2.65, 3.

### Step 2: Data Preprocessing

The values of features X1-X6 are in different scales. The feature in a large scale would have a huge influence on the target value prediction. We shall normalize the values of different features into a uniform scale to balance the contributions of different features to target value prediction. Here we use the [MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) to scale the feature values into the range of $[0,1]$. Another choice for feature normalization is [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).

In [44]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

In [45]:
X

array([[0.27292576, 0.73059361, 0.00951267, 1.        , 0.61694135,
        0.71932284],
       [0.27292576, 0.44520548, 0.04380939, 0.9       , 0.5849491 ,
        0.71145137],
       [1.        , 0.30365297, 0.08331505, 0.5       , 0.67123122,
        0.75889584],
       ...,
       [0.63646288, 0.42922374, 0.05686115, 0.7       , 0.57149782,
        0.71522536],
       [0.36353712, 0.18493151, 0.0125958 , 0.5       , 0.42014057,
        0.72395946],
       [0.90938865, 0.14840183, 0.0103754 , 0.9       , 0.51211827,
        0.75016174]], shape=(414, 6))

### Step 3: Train-Test Split

We randomly split the data $X$ and $y$ into training and test sets with the ratio $1:1$.

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=0)

### Step 4: House Price Prediction with Gaussian Process Regression

Read [Scikit-Learn's GaussianProcessRegressor API](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html), and implement the Gaussian process regression model with RBF kernel $k_{\mathrm{SE}}\left(\mathbf{x}_{i}, \mathbf{x}_{j}\right)=\sigma_f^{2} \exp \left(-\frac{1}{2 \ell^{2}}\left\|\mathbf{x}_{i}-\mathbf{x}_{j}\right\|_2^{2}\right)$, as well as the additive i.i.d Gaussian noise with zero mean and variance $\sigma_n^2$. 

**Task 1**: Implement the Gaussian process regression model with the hyperparameter setting: signal variance $\sigma_f^{2}=1.5$, length-scale $\ell=1.5$ and noise variance $\sigma_n^2=0.01$. Keep the hyperparameters fixed when fitting the model. 

In [47]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import ConstantKernel, RBF

# Train the Gaussian process regression model with the training data (X_train and y_train)
kernel = ConstantKernel(constant_value=1.5) * RBF(length_scale=1.5)
gpr1 = GaussianProcessRegressor(kernel=kernel, alpha=0.01, optimizer=None)

gpr1.fit(X_train, y_train)

GaussianProcessRegressor(alpha=0.01, kernel=1.22**2 * RBF(length_scale=1.5),
                         optimizer=None)

In [48]:
# Predict the target values for the test data
y_pred = gpr1.predict(X_test)
y_pred

array([2.73576386, 1.24529008, 2.98469622, 1.24269651, 3.2920239 ,
       2.79648627, 2.96097889, 2.56218762, 3.37531305, 3.11460733,
       3.09925669, 2.61161089, 2.65420539, 2.84850587, 3.40339705,
       2.98305523, 2.696414  , 2.94851879, 2.61608829, 2.8939753 ,
       3.46001507, 1.74849652, 2.36608056, 3.1400591 , 3.41524596,
       2.85323413, 2.90677349, 1.47119426, 3.50707603, 1.34214332,
       3.14512487, 2.37019961, 3.14637916, 3.25394375, 2.8143156 ,
       1.87046779, 3.09806743, 2.36580013, 3.32315839, 0.88372403,
       3.86424709, 2.47175158, 1.87417203, 3.15839737, 1.33052203,
       2.97956743, 2.43887602, 1.2469148 , 1.93014381, 3.51235308,
       3.75622112, 2.33580372, 2.88587098, 1.46799088, 1.71426505,
       2.32619729, 3.63982163, 2.65053885, 2.89065728, 2.02484028,
       2.70778452, 3.29952551, 2.78929758, 3.23115186, 2.44574919,
       1.46237651, 1.10889718, 2.24515123, 3.29562613, 2.79648627,
       1.81861802, 3.29032179, 3.17088272, 1.68763481, 2.98849

In [49]:
# Compare the ground-truth and predicted target values
pd.DataFrame({'y_test': y_test, 'y_pred': y_pred})

y_test    y_pred
0      3.02  2.735764
1      0.96  1.245290
2      3.07  2.984696
3      1.04  1.242697
4      3.35  3.292024
..      ...       ...
202    2.47  2.618869
203    1.97  1.434335
204    2.24  2.815379
205    3.15  3.298686
206    1.59  1.684613

[207 rows x 2 columns]

Compute the $R^2$ score as an evaluation of the trained GaussianProcessRegressor model. The best possible $R^2$ score is 1.0

In [50]:
score = gpr1.score(X_test, y_test)
score

0.7125702112337001

In [51]:
# Print the log marginal likehood value of the fitted model
lml = gpr1.log_marginal_likelihood_value_
lml

np.float64(-2842.653598822927)

**Task 2**: Use [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s log marginal likelihood value to select the best hyperparameter setting when signal variance $\sigma_f^2$ varies in the set $\{1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5\}$, length-scale $\ell$ in $\{1, 2, 3, 4, 5\}$ and noise variance $\sigma_n^2$ in $\{0.0001,0.001,0.01,0.1,1\}$. Write a grid search program to do model selection, do not use [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s automatic hyperparameter optimizer, report the best hyperparameter setting as well as the corresponding model's prediction performance. 

In [52]:
# Use grid search to find the best hyperparameter setting
from sklearn.model_selection import GridSearchCV

signal_variance_values = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
length_scale_values = [1, 2, 3, 4, 5]
noise_variance_values = [0.0001,0.001,0.01,0.1,1]

param_grid = {
    'kernel': [ConstantKernel(constant_value=sv) * RBF(length_scale=ls)
                for sv in signal_variance_values for ls in length_scale_values],
    'alpha': noise_variance_values
}

gpr = GaussianProcessRegressor(optimizer=None)

grid_search = GridSearchCV(estimator=gpr, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)

gpr2 = grid_search.best_estimator_
gpr2

GaussianProcessRegressor(alpha=0.0001, kernel=1.41**2 * RBF(length_scale=5),
                         optimizer=None)

In [53]:
# Predict the target values for the test data
y_pred = gpr2.predict(X_test)
y_pred

array([2.73205969, 1.3170911 , 2.9830509 , 1.32674467, 3.24277272,
       2.74659285, 2.95121496, 2.58364505, 3.35644384, 3.10995838,
       3.10070954, 2.61521957, 2.64233132, 2.83597163, 3.39464267,
       2.99727448, 2.68030335, 3.05712332, 2.58522641, 2.88839204,
       3.55757554, 1.74149856, 2.40347672, 3.12587104, 3.39825345,
       2.84349306, 2.92429249, 1.40587002, 3.4762241 , 1.34208875,
       3.18942718, 2.3122833 , 3.23919284, 3.26747825, 2.81236394,
       1.85556019, 3.07327938, 2.38913685, 3.30553234, 1.10015128,
       3.85387977, 2.50502082, 1.81012093, 3.16072115, 1.32931927,
       3.02650712, 2.46656563, 1.24940044, 1.91880092, 3.59436574,
       3.74867402, 2.34683148, 2.90403413, 1.49920452, 1.70069877,
       2.30504053, 3.61175872, 2.64953247, 2.89465898, 1.99540436,
       2.70907444, 3.27288943, 2.76083269, 3.21031391, 2.42787729,
       1.49161511, 1.22405823, 2.25112164, 3.33484674, 2.74659285,
       1.78544016, 3.28209661, 3.12740756, 1.613304  , 2.98569

In [54]:
# Compare the ground-truth and predicted target values
pd.DataFrame({'y_test': y_test, 'y_pred': y_pred})

y_test    y_pred
0      3.02  2.732060
1      0.96  1.317091
2      3.07  2.983051
3      1.04  1.326745
4      3.35  3.242773
..      ...       ...
202    2.47  2.593184
203    1.97  1.409362
204    2.24  2.833103
205    3.15  3.323353
206    1.59  1.738027

[207 rows x 2 columns]

Compute the $R^2$ score as an evaluation of the selected best GaussianProcessRegressor model. The best possible $R^2$ score is 1.0.

In [55]:
score = gpr2.score(X_test, y_test)
score

0.7090758867030588

In [56]:
# Print the log marginal likehood value of the selected best model
lml = gpr2.log_marginal_likelihood_value_
lml

np.float64(-308542.4269400195)

In [57]:
# Print the best model's hyperparameter setting
print(gpr2.get_params)

<bound method BaseEstimator.get_params of GaussianProcessRegressor(alpha=0.0001, kernel=1.41**2 * RBF(length_scale=5),
                         optimizer=None)>


**Task 3**: Use [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s automatic hyperparameter optimizer to find the best hyperparameter setting when $\sigma_f^2$ and $\ell$ both vary in the range $[1,5]$, while $\sigma_n^2$ is fixed as 0.01. Report the best hyperparameter setting as well as the corresponding model's prediction performance. 

In [58]:
# Train the Gaussian process regression model with the activated hyperparameter optimizer
kernel = ConstantKernel(1.0, (1.0, 5.0)) * RBF(1.0, (1.0, 5.0)) 
gpr3 = GaussianProcessRegressor(kernel=kernel, alpha=0.01)

gpr3.fit(X_train, y_train)

GaussianProcessRegressor(alpha=0.01, kernel=1**2 * RBF(length_scale=1))

In [59]:
# Predict the target values for the test data
y_pred = gpr3.predict(X_test)
y_pred

array([2.64308723, 0.79584055, 2.8858282 , 0.75374471, 3.6687125 ,
       2.86119872, 3.0291644 , 2.66914092, 3.2615364 , 3.09524481,
       2.93706754, 2.54708478, 2.61482735, 2.88958038, 3.54437099,
       3.23111684, 2.55878728, 2.08436815, 2.60193749, 2.90023682,
       3.47333092, 1.6829693 , 1.84048491, 3.25713592, 3.4985541 ,
       2.68484325, 2.64666409, 1.51357311, 3.61853815, 1.54048933,
       3.12764473, 2.20351229, 2.69478755, 3.71453332, 2.55185216,
       1.8061682 , 3.32734235, 2.16235773, 3.32173464, 0.44857143,
       3.91861847, 2.54153146, 1.8891986 , 3.41571433, 1.29795033,
       2.821601  , 2.05555063, 1.21518104, 1.80907819, 3.52539119,
       3.88760257, 2.04594184, 2.63710471, 1.02293274, 1.66522961,
       2.36732922, 3.78859226, 2.54992002, 2.77840165, 1.82931754,
       2.58819486, 3.54779299, 2.96716185, 3.23134679, 2.47610633,
       1.4504833 , 1.22320546, 2.26428598, 3.33434216, 2.86119872,
       1.64445879, 3.44128957, 3.47539377, 1.72380349, 3.05482

In [60]:
# Compare the ground-truth and predicted target values
pd.DataFrame({'y_test': y_test, 'y_pred': y_pred})

y_test    y_pred
0      3.02  2.643087
1      0.96  0.795841
2      3.07  2.885828
3      1.04  0.753745
4      3.35  3.668712
..      ...       ...
202    2.47  2.617107
203    1.97  1.567128
204    2.24  2.705011
205    3.15  3.221417
206    1.59  1.688389

[207 rows x 2 columns]

Compute the $R^2$ score as an evaluation of the optimized GaussianProcessRegressor model. The best possible $R^2$ score is 1.0.

In [61]:
score = gpr3.score(X_test, y_test)
score

0.6743255944316389

In [62]:
# Print the log marginal likelihood value of the optimized model
lml = gpr3.log_marginal_likelihood_value_
lml

np.float64(-2272.977341861257)

In [63]:
# Print the optimized hyperparameters
print(gpr3.get_params)

<bound method BaseEstimator.get_params of GaussianProcessRegressor(alpha=0.01, kernel=1**2 * RBF(length_scale=1))>


Think about why the optimized models (by grid search and automatic optimizer) perform better or worse than the fixed-hyperparameter model.

**Futher Exploration (Optional)**:
+ Choose [DotProduct](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.DotProduct.html) as the kernel function, evaluate the model's performance with the default kernel hyperparameter setting, and use grid search and [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s hyperparameter optimizer to find the best hyperparameter setting. 

In [64]:
from sklearn.gaussian_process.kernels import DotProduct

# Grid Search
signal_variance_values = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
noise_variance_values = [0.0001,0.001,0.01,0.1,1]

param_grid = {
    'kernel': [ConstantKernel(constant_value=sv) * DotProduct()
                for sv in signal_variance_values],
    'alpha': noise_variance_values
}

gpr = GaussianProcessRegressor(optimizer=None)

grid_search = GridSearchCV(estimator=gpr, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)

gpr4 = grid_search.best_estimator_
print(gpr4.get_params)

# Optimizer
kernel = ConstantKernel(1.0, (1.0, 5.0)) * DotProduct()
gpr5 = GaussianProcessRegressor(kernel=kernel, alpha=0.01)
print(gpr5.get_params)

<bound method BaseEstimator.get_params of GaussianProcessRegressor(alpha=0.1, kernel=1**2 * DotProduct(sigma_0=1),
                         optimizer=None)>
<bound method BaseEstimator.get_params of GaussianProcessRegressor(alpha=0.01, kernel=1**2 * DotProduct(sigma_0=1))>
